project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
  resources:
    - .well-known/
    - _redirects
website:
  description: "A personal website"
  site-url: https://rorylawless.com
  title: "Rory Lawless"
  favicon: assets/favicon.svg
  repo-url: https://codeberg.org/RoryLawless/website/
  page-footer:
    background: "#fbf5f5"
    foreground: "#070a0c"
    center: "Made with [Quarto](https://quarto.org/) in DC via LDN. 
    

    [Website](https://rorylawless.com/) Â© 2025-2026 by [Rory
    Lawless](about.qmd) is licensed under [CC
    BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  search: false
  draft-mode: gone
  navbar:
    background: "#24617a"
    foreground: "#fbf5f5"
    right:
      - icon: file-person-fill
        text: "About"
        href: about.qmd
        aria-label: "About"
      - icon: envelope-heart-fill
        href: mailto:rory@rorylawless.com
        aria-label: "email Rory"
      - icon: bluesky
        href: https://bsky.app/profile/rorylawless.com
        aria-label: "Bluesky"
      - icon: linkedin
        href: https://www.linkedin.com/in/rory-lawless/
        aria-label: "LinkedIn"
      - icon: git
        href: https://codeberg.org/RoryLawless/
        aria-label: "Codeberg"
format:
  html:
    theme:
      - none
      - assets/custom.scss
    highlight-style: a11y
    code-copy: true
    backgroundcolor: "#fbf5f5"
    mainfont: "Lato"
    fontcolor: "#070a0c"
    fontsize: 14pt
    linkcolor: "#183e4d"
    code-overflow: wrap
    email-obfuscation: references
metadata-files:
  - drafts.yml